import type { Lang } from "@/lib/i18n";

/**
 * Ready-made checklists offered when a project is empty, one per trade /
 * market we sell to. Sections are created in the owner's language (so their
 * language is the source language for AI translation).
 */
export type ProjectTemplate = {
  key: string;
  name: Record<Lang, string>;
  sections: Record<Lang, string[]>;
};

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    key: "renovation",
    name: {
      en: "Full renovation",
      it: "Ristrutturazione completa",
      es: "Renovación completa",
    },
    sections: {
      en: [
        "Site preparation",
        "Demolition",
        "Foundation",
        "Framing",
        "Roofing",
        "Windows & doors",
        "Electrical",
        "Plumbing",
        "HVAC",
        "Insulation & drywall",
        "Finishes",
        "Final inspection",
      ],
      it: [
        "Preparazione del cantiere",
        "Demolizione",
        "Fondazioni",
        "Struttura",
        "Copertura",
        "Finestre e porte",
        "Impianto elettrico",
        "Impianto idraulico",
        "Climatizzazione",
        "Isolamento e cartongesso",
        "Finiture",
        "Collaudo finale",
      ],
      es: [
        "Preparación del terreno",
        "Demolición",
        "Cimentación",
        "Estructura",
        "Techado",
        "Ventanas y puertas",
        "Instalación eléctrica",
        "Fontanería",
        "Climatización",
        "Aislamiento y tablaroca",
        "Acabados",
        "Inspección final",
      ],
    },
  },
  {
    key: "kitchen",
    name: {
      en: "Kitchen remodel",
      it: "Rifacimento cucina",
      es: "Remodelación de cocina",
    },
    sections: {
      en: [
        "Design & measurements",
        "Demolition",
        "Rough plumbing",
        "Rough electrical",
        "Drywall & paint",
        "Flooring",
        "Cabinets",
        "Countertops",
        "Backsplash & tile",
        "Appliances",
        "Plumbing fixtures",
        "Punch list & cleanup",
      ],
      it: [
        "Progetto e misure",
        "Demolizione",
        "Impianto idraulico grezzo",
        "Impianto elettrico grezzo",
        "Cartongesso e tinteggiatura",
        "Pavimenti",
        "Mobili della cucina",
        "Piani di lavoro",
        "Paraschizzi e piastrelle",
        "Elettrodomestici",
        "Rubinetteria",
        "Rifiniture e pulizia",
      ],
      es: [
        "Diseño y medidas",
        "Demolición",
        "Plomería en obra negra",
        "Electricidad en obra negra",
        "Tablaroca y pintura",
        "Pisos",
        "Gabinetes",
        "Encimeras",
        "Salpicadero y azulejos",
        "Electrodomésticos",
        "Grifería y accesorios",
        "Detalles finales y limpieza",
      ],
    },
  },
  {
    key: "bathroom",
    name: {
      en: "Bathroom remodel",
      it: "Rifacimento bagno",
      es: "Remodelación de baño",
    },
    sections: {
      en: [
        "Design & fixture selection",
        "Demolition",
        "Rough plumbing",
        "Rough electrical",
        "Waterproofing",
        "Tile",
        "Vanity & cabinets",
        "Plumbing fixtures",
        "Glass & mirrors",
        "Paint & finishes",
        "Punch list",
      ],
      it: [
        "Progetto e scelta dei sanitari",
        "Demolizione",
        "Impianto idraulico grezzo",
        "Impianto elettrico grezzo",
        "Impermeabilizzazione",
        "Piastrelle",
        "Mobile bagno",
        "Rubinetteria e sanitari",
        "Vetri e specchi",
        "Tinteggiatura e finiture",
        "Rifiniture finali",
      ],
      es: [
        "Diseño y selección de accesorios",
        "Demolición",
        "Plomería en obra negra",
        "Electricidad en obra negra",
        "Impermeabilización",
        "Azulejos",
        "Mueble de baño",
        "Grifería y sanitarios",
        "Vidrios y espejos",
        "Pintura y acabados",
        "Detalles finales",
      ],
    },
  },
  {
    key: "landscaping",
    name: {
      en: "Landscaping",
      it: "Sistemazione esterna",
      es: "Paisajismo",
    },
    sections: {
      en: [
        "Site survey & design",
        "Clearing & demolition",
        "Grading & drainage",
        "Irrigation",
        "Patios & walkways",
        "Fencing & walls",
        "Outdoor lighting",
        "Soil & planting beds",
        "Trees & shrubs",
        "Lawn",
        "Cleanup & final walkthrough",
      ],
      it: [
        "Rilievo e progetto",
        "Sgombero e rimozioni",
        "Livellamento e drenaggio",
        "Irrigazione",
        "Pavimentazioni e vialetti",
        "Recinzioni e muretti",
        "Illuminazione esterna",
        "Terreno e aiuole",
        "Alberi e arbusti",
        "Prato",
        "Pulizia e sopralluogo finale",
      ],
      es: [
        "Levantamiento y diseño",
        "Limpieza y demolición",
        "Nivelación y drenaje",
        "Riego",
        "Patios y andadores",
        "Cercas y muros",
        "Iluminación exterior",
        "Tierra y jardineras",
        "Árboles y arbustos",
        "Césped",
        "Limpieza y recorrido final",
      ],
    },
  },
  {
    key: "painting",
    name: {
      en: "Painting",
      it: "Tinteggiatura",
      es: "Pintura",
    },
    sections: {
      en: [
        "Estimate & color selection",
        "Surface prep & repairs",
        "Masking & protection",
        "Priming",
        "Interior walls & ceilings",
        "Trim & doors",
        "Exterior siding",
        "Exterior trim",
        "Touch-ups & inspection",
        "Cleanup",
      ],
      it: [
        "Preventivo e scelta colori",
        "Preparazione e stuccature",
        "Mascherature e protezioni",
        "Fondo",
        "Pareti e soffitti interni",
        "Cornici e porte",
        "Facciata esterna",
        "Rifiniture esterne",
        "Ritocchi e verifica",
        "Pulizia",
      ],
      es: [
        "Presupuesto y selección de colores",
        "Preparación y resanes",
        "Enmascarado y protección",
        "Imprimación",
        "Muros y techos interiores",
        "Molduras y puertas",
        "Fachada exterior",
        "Detalles exteriores",
        "Retoques e inspección",
        "Limpieza",
      ],
    },
  },
  {
    key: "roofing",
    name: {
      en: "Roofing",
      it: "Rifacimento tetto",
      es: "Techado",
    },
    sections: {
      en: [
        "Inspection & estimate",
        "Material delivery",
        "Tear-off",
        "Deck repairs",
        "Underlayment & flashing",
        "Roof covering install",
        "Vents & penetrations",
        "Gutters & downspouts",
        "Final inspection",
        "Cleanup & haul-away",
      ],
      it: [
        "Sopralluogo e preventivo",
        "Consegna materiali",
        "Rimozione del manto",
        "Riparazione del piano di posa",
        "Guaina e scossaline",
        "Posa del manto di copertura",
        "Sfiati e attraversamenti",
        "Grondaie e pluviali",
        "Collaudo finale",
        "Pulizia e smaltimento",
      ],
      es: [
        "Inspección y presupuesto",
        "Entrega de materiales",
        "Retiro del techo viejo",
        "Reparación de la cubierta",
        "Membrana y tapajuntas",
        "Instalación del techado",
        "Ventilas y penetraciones",
        "Canalones y bajantes",
        "Inspección final",
        "Limpieza y acarreo",
      ],
    },
  },
  {
    key: "overseas",
    name: {
      en: "Overseas renovation",
      it: "Ristrutturazione dall'estero",
      es: "Renovación en el extranjero",
    },
    sections: {
      en: [
        "Purchase & due diligence",
        "Permits & approvals",
        "Design & surveys",
        "Contractor selection",
        "Structural work",
        "Roof & exterior",
        "Electrical, plumbing & heating",
        "Windows & doors",
        "Interior finishes",
        "Furnishing",
        "Utilities & handover",
        "Final walkthrough",
      ],
      it: [
        "Acquisto e verifiche",
        "Permessi e pratiche",
        "Progetto e rilievi",
        "Scelta dell'impresa",
        "Opere strutturali",
        "Tetto ed esterni",
        "Impianti elettrico, idraulico e riscaldamento",
        "Finestre e porte",
        "Finiture interne",
        "Arredamento",
        "Utenze e consegna",
        "Sopralluogo finale",
      ],
      es: [
        "Compra y verificaciones",
        "Permisos y trámites",
        "Diseño y levantamientos",
        "Selección del contratista",
        "Obra estructural",
        "Techo y exteriores",
        "Electricidad, plomería y calefacción",
        "Ventanas y puertas",
        "Acabados interiores",
        "Mobiliario",
        "Servicios y entrega",
        "Recorrido final",
      ],
    },
  },
  {
    key: "design",
    name: {
      en: "Interior design",
      it: "Interior design",
      es: "Diseño de interiores",
    },
    sections: {
      en: [
        "Concept & mood boards",
        "Client approvals",
        "Space planning",
        "Materials & finishes",
        "Furniture & fixtures",
        "Procurement & orders",
        "Trades coordination",
        "Deliveries",
        "Installation",
        "Styling & photography",
        "Client handover",
      ],
      it: [
        "Concept e moodboard",
        "Approvazioni del cliente",
        "Progettazione degli spazi",
        "Materiali e finiture",
        "Arredi e complementi",
        "Acquisti e ordini",
        "Coordinamento delle imprese",
        "Consegne",
        "Installazione",
        "Styling e fotografia",
        "Consegna al cliente",
      ],
      es: [
        "Concepto y moodboards",
        "Aprobaciones del cliente",
        "Distribución de espacios",
        "Materiales y acabados",
        "Mobiliario y accesorios",
        "Compras y pedidos",
        "Coordinación de gremios",
        "Entregas",
        "Instalación",
        "Estilismo y fotografía",
        "Entrega al cliente",
      ],
    },
  },
];
